### ISSUE TITLE
IndexError: Too many indices: 2-dimensional array indexed with 3 regular indices.

### ISSUE THREAD

**Issue by scy5335** [Benjamin-Walker/log-neural-cdes#62]
Hi, Ben,

I generate toy dataset and modify the dataset_name in the "run_experiment.py" to "signature1", "signature2", "signature3", "signature4". The code can successfully create "signature1". However, when creating "signature2", it will cause "IndexError: Too many indices: 2-dimensional array indexed with 3 regular indices."
![image](https://github.com/user-attachments/assets/afef6c1e-6161-48c5-ad2f-2b38ffde96cb)
How can I solve this problem?

Best Regards

**Comment by Benjamin-Walker** [comment]
Hi Su Chengye,

I was not able to recreate your issue on a fresh clone of the github repo. It seems your line 319 in `data_dir/datasets.py` is slightly different to the version on github.

Your line reads
```
labels = ((jnp.sign(labels[:, 2, 5]) + 1) / 2).astype(int)
```

Whereas the version on Github is
```
labels = ((jnp.sign(labels[1][:, 2, 5]) + 1) / 2).astype(int)
```

When signax generates the signature for each path, it creates a list where the first element is the level 1 signatures for each path, the second element is the level 2 signatures, etc. This is why for `signature2`, the second element of labels is extracted `labels[1]`, before the relevant element of the level-2 signature is extracted.

In order to resolve your issue, I would check that you have signax 0.1.1 installed and are using the latest version of the code.

Hope this helps!

**Comment by scy5335** [comment]
Hi Ben,
Thanks for your reply! 
I modify the code, but it still causes a bug.
![image](https://github.com/user-attachments/assets/e62f6df5-e7fa-4eb0-91ce-45d820afbc48)
I have checked the version of signax, it's 0.1.1. What can I do next?
Regards

**Comment by Benjamin-Walker** [comment]
Given this information, I believe this is likely an issue in `data_dir/toy_dataset.py`. Have you made any modifications to this file? If not, could you check the type and shape of labels? It should be a list of length 4, with the elements of the list being jax numpy arrays of size (100000, 6), (100000, 6, 6), (100000, 6, 6, 6), and (100000, 6, 6, 6, 6).

**Comment by scy5335** [comment]
Hi Ben,
The problem may cause by the wrong type of signax originally. And then I run the "toy_dataset.py" under the folder "data_dir". That is my fault. The bug is fixed now. Thanks sincerely for your reply!
Regards

**Comment by Benjamin-Walker** [comment]
Hi Su Chengye, 

I see! Glad the error is resolved, and I am happy to help.

Kind regards,

Ben
